name: ${project.name}
main: ${project.groupId}.RPCore
description: ${project.description}
version: ${project.version}
author: roby08
depend: [PlaceholderAPI]
api-version: 1.18
commands:
  card:
    description: Display character information.
  character:
    description: Change character information.
  roll:
    description: Roll a random number.
  shout:
    description: Sets chat channel to shout.
  whisper:
    description: Sets chat channel to whisper.
  quiet:
    description: Sets chat channel to quiet.
  ooc:
    description: Sets chat channel to ooc.
  looc:
    description: Sets chat channel to local ooc.
  wooc:
    description: Sets chat channel wooc.
  me:
    description: Sets chat channel to me.
  defaultchat:
    description: Sets chat channel to default.
  setrole:
    description: Sets the role of a player.
  rpreload:
    description: Reloads the RPCore config.

