name: ${project.name}
main: ${project.groupId}.RPCore
description: ${project.description}
version: ${project.version}
author: roby08
api-version: 1.18
commands:
  plot:
    description: plot-tools main command